server:
  port: 8088
  display-name: code-generator

spring:
  application:
    name: mybatisplus-generator-web
  thymeleaf:
    cache: false
    prefix: classpath:/templates
    mode: LEGACYHTML5
    suffix: .html
logging:
  level: debug
